# Generated by Django 4.0.4 on 2022-05-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('fecha_fundacion', models.DateField()),
                ('estadio', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('equipo', models.CharField(max_length=100)),
                ('posicion', models.CharField(max_length=20)),
                ('valor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Torneos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('pais', models.CharField(max_length=50)),
                ('duracion', models.IntegerField()),
                ('campeon', models.CharField(max_length=100)),
            ],
        ),
    ]
